### ISSUE TITLE
Feature documentation: Update README.md

### ISSUE THREAD

**Issue by AnjaSlama** [rsbaher1/ENSF619.2-RSVP_Module#24]
Update the installation section to solve the following errors:

- Node installation
- zsh: command not found: firebase
- AssertionError [ERR_ASSERTION]: Firebase DB URL is required.  

Update the common errors section in regards to the Firebase Emulator

**Comment by rsbaher1** [comment]
@AnjaSlama There is a new branch created for you to work on this issue: https://github.com/rsbaher1/ENSF619.2-RSVP_Module/tree/issue-24-Feature_documentation_Update_README_md

I don't think github lets you create a pull request until there's a difference between the issue branch and dev.

**Comment by rsbaher1** [comment]
Pull Request successfully merged
